/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahehsanuragh;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sssssssssssssss
 */
public class studentsearch extends javax.swing.JFrame {

    String BOOKNAME,NAMEOFSTUDENT,clss;
    String isbn3;
    /**
     * Creates new form studentsearch
     */
    public studentsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ISBN3 = new javax.swing.JTextField();
        Button1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NFS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BN3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CLSSS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SEARCH FOR STUDENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 46, -1, -1));

        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 108, 47, -1));

        ISBN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBN3ActionPerformed(evt);
            }
        });
        getContentPane().add(ISBN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 105, 295, -1));

        Button1.setText("SEARCH");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 104, -1, -1));

        jLabel3.setText("NAME OF STUDENT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 178, -1, -1));
        getContentPane().add(NFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 175, 295, -1));

        jLabel4.setText("BOOK NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 257, -1, -1));
        getContentPane().add(BN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 254, 295, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 327, -1, -1));

        jLabel5.setText("CLASS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 216, 59, -1));
        getContentPane().add(CLSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 213, 295, -1));

        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 680, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        homepage hp=new homepage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
          
        try {
            // TODO add your handling code here:
            isbn3=ISBN3.getText();
            
                                            
            
            Connection g=databaseconnection.getConnection();
            
            Statement pt=g.createStatement();
                            
            
            String query="SELECT * FROM book2 WHERE isbn='"+isbn3+"'";
            
            ResultSet sp=pt.executeQuery(query);
            
            if(sp.next())
            {
               
                NAMEOFSTUDENT=sp.getString("studentname");
                NFS.setText(NAMEOFSTUDENT);
                
                clss=sp.getString("class");
                CLSSS.setText(clss);
                
                 BOOKNAME=sp.getString("bookname");
                BN3.setText(BOOKNAME);
            }
            else
            {
                
                NAMEOFSTUDENT=sp.getString(null);
                
                 CLSSS.setText(null);
                
                
                BOOKNAME=sp.getString(null);
                
                
            }
                
                
                  } catch (SQLException ex) {
                Logger.getLogger(studentsearch.class.getName()).log(Level.SEVERE, null, ex);
            }
                                         
        
    }//GEN-LAST:event_Button1ActionPerformed

    private void ISBN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBN3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BN3;
    private javax.swing.JButton Button1;
    private javax.swing.JTextField CLSSS;
    private javax.swing.JTextField ISBN3;
    private javax.swing.JTextField NFS;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
